const kecamatanData = {
    "01": [  // Kabupaten Banjarnegara
        { nama: "Banjarmangu", kode: "E01" },
        { nama: "Banjarnegara", kode: "E02" },
        { nama: "Batur", kode: "E03" },
        { nama: "Bawang", kode: "E04" },
        { nama: "Kalibening", kode: "E05" },
        { nama: "Karangkobar", kode: "E06" },
        { nama: "Madukara", kode: "E07" },
        { nama: "Mandiraja", kode: "E08" },
        { nama: "Pagedongan", kode: "E09" },
        { nama: "Pejawaran", kode: "E10" },
        { nama: "Punggelan", kode: "E11" },
        { nama: "Purwareja Klampok", kode: "E12" },
        { nama: "Rakit", kode: "E13" },
        { nama: "Sigaluh", kode: "E14" },
        { nama: "Susukan", kode: "E15" },
        { nama: "Wanadadi", kode: "E16" },
        { nama: "Wanayasa", kode: "E17" }
    ],
    "02": [  // Kabupaten Banyumas
        { nama: "Ajibarang", kode: "E18" },
        { nama: "Banyumas", kode: "E19" },
        { nama: "Baturraden", kode: "E20" },
        { nama: "Cilongok", kode: "E21" },
        { nama: "Gumelar", kode: "E22" },
        { nama: "Jatilawang", kode: "E23" },
        { nama: "Kalibagor", kode: "E24" },
        { nama: "Karanglewas", kode: "E25" },
        { nama: "Kebasen", kode: "E26" },
        { nama: "Kedungbanteng", kode: "E27" },
        { nama: "Kembaran", kode: "E28" },
        { nama: "Lumbir", kode: "E29" },
        { nama: "Patikraja", kode: "E30" },
        { nama: "Pekuncen", kode: "E31" },
        { nama: "Purwojati", kode: "E32" },
        { nama: "Rawalo", kode: "E33" },
        { nama: "Sokaraja", kode: "E34" },
        { nama: "Somagede", kode: "E35" },
        { nama: "Sumbang", kode: "E36" },
        { nama: "Sumpiuh", kode: "E37" },
        { nama: "Tambak", kode: "E38" },
        { nama: "Wangon", kode: "E39" }
    ],
    "03": [  // Kabupaten Batang
        { nama: "Banyuputih", kode: "E40" },
        { nama: "Batang", kode: "E41" },
        { nama: "Bandar", kode: "E42" },
        { nama: "Bawang", kode: "E43" },
        { nama: "Blado", kode: "E44" },
        { nama: "Gringsing", kode: "E45" },
        { nama: "Kandeman", kode: "E46" },
        { nama: "Limpung", kode: "E47" },
        { nama: "Pecalungan", kode: "E48" },
        { nama: "Reban", kode: "E49" },
        { nama: "Subah", kode: "E50" },
        { nama: "Tersono", kode: "E51" },
        { nama: "Warungasem", kode: "E52" },
        { nama: "Wonotunggal", kode: "E53" }
    ],
    "04": [  // Kabupaten Blora
        { nama: "Blora", kode: "E54" },
        { nama: "Bogorejo", kode: "E55" },
        { nama: "Cepu", kode: "E56" },
        { nama: "Japah", kode: "E57" },
        { nama: "Jepon", kode: "E58" },
        { nama: "Jiken", kode: "E59" },
        { nama: "Kedungtuban", kode: "E60" },
        { nama: "Kradenan", kode: "E61" },
        { nama: "Kunduran", kode: "E62" },
        { nama: "Ngawen", kode: "E63" },
        { nama: "Randublatung", kode: "E64" },
        { nama: "Sambong", kode: "E65" },
        { nama: "Todanan", kode: "E66" },
        { nama: "Tunjungan", kode: "E67" }
    ],
    "05": [  // Kabupaten Boyolali
        { nama: "Ampel", kode: "E68" },
        { nama: "Andong", kode: "E69" },
        { nama: "Boyolali", kode: "E70" },
        { nama: "Cepogo", kode: "E71" },
        { nama: "Juwangi", kode: "E72" },
        { nama: "Karanggede", kode: "E73" },
        { nama: "Kemusu", kode: "E74" },
        { nama: "Klego", kode: "E75" },
        { nama: "Mojosongo", kode: "E76" },
        { nama: "Musuk", kode: "E77" },
        { nama: "Ngemplak", kode: "E78" },
        { nama: "Nogosari", kode: "E79" },
        { nama: "Sambi", kode: "E80" },
        { nama: "Sawit", kode: "E81" },
        { nama: "Selo", kode: "E82" },
        { nama: "Teras", kode: "E83" },
        { nama: "Wonosegoro", kode: "E84" }
    ],
    "06": [  // Kabupaten Brebes
        { nama: "Banjarharjo", kode: "E85" },
        { nama: "Bantarkawung", kode: "E86" },
        { nama: "Brebes", kode: "E87" },
        { nama: "Bulakamba", kode: "E88" },
        { nama: "Bumiayu", kode: "E89" },
        { nama: "Jatibarang", kode: "E90" },
        { nama: "Kersana", kode: "E91" },
        { nama: "Ketanggungan", kode: "E92" },
        { nama: "Larangan", kode: "E93" },
        { nama: "Losari", kode: "E94" },
        { nama: "Paguyangan", kode: "E95" },
        { nama: "Salem", kode: "E96" },
        { nama: "Sirampog", kode: "E97" },
        { nama: "Songgom", kode: "E98" },
        { nama: "Tanjung", kode: "E99" },
        { nama: "Tonjong", kode: "E100" },
        { nama: "Wanasari", kode: "E101" }
    ],
    "07": [  // Kabupaten Cilacap
        { nama: "Adipala", kode: "E102" },
        { nama: "Bantarsari", kode: "E103" },
        { nama: "Binangun", kode: "E104" },
        { nama: "Cilacap Selatan", kode: "E105" },
        { nama: "Cilacap Tengah", kode: "E106" },
        { nama: "Cilacap Utara", kode: "E107" },
        { nama: "Cipari", kode: "E108" },
        { nama: "Dayeuhluhur", kode: "E109" },
        { nama: "Gandrungmangu", kode: "E110" },
        { nama: "Jeruklegi", kode: "E111" },
        { nama: "Kampung Laut", kode: "E112" },
        { nama: "Karangpucung", kode: "E113" },
        { nama: "Kawunganten", kode: "E114" },
        { nama: "Kesugihan", kode: "E115" },
        { nama: "Kroya", kode: "E116" },
        { nama: "Majenang", kode: "E117" },
        { nama: "Maos", kode: "E118" },
        { nama: "Nusawungu", kode: "E119" },
        { nama: "Patimuan", kode: "E120" },
        { nama: "Pengadegan", kode: "E121" },
        { nama: "Sidareja", kode: "E122" },
        { nama: "Sukabumi", kode: "E123" },
        { nama: "Wanareja", kode: "E124" }
    ],
    "08": [  // Kabupaten Demak
        { nama: "Bintoro", kode: "E125" },
        { nama: "Demak", kode: "E126" },
        { nama: "Guntur", kode: "E127" },
        { nama: "Karangawun", kode: "E128" },
        { nama: "Kebonagung", kode: "E129" },
        { nama: "Mijen", kode: "E130" },
        { nama: "Sayung", kode: "E131" },
        { nama: "Wonosalam", kode: "E132" },
        { nama: "Dempet", kode: "E133" },
        { nama: "Bonang", kode: "E134" },
        { nama: "Dempet", kode: "E135" },
        { nama: "Karanganyar", kode: "E136" },
        { nama: "Sukorejo", kode: "E137" }
    ],
    "09": [  // Kabupaten Grobogan
		{ nama: "Brati", kode: "E138" },
		{ nama: "Gabus", kode: "E139" },
		{ nama: "Gubug", kode: "E140" },
		{ nama: "KarangRayung", kode: "E141" },
		{ nama: "Kedungjati", kode: "E142" },
		{ nama: "Klambu", kode: "E143" },
		{ nama: "Kradenan", kode: "E144" },
		{ nama: "Ngaringan", kode: "E145" },
		{ nama: "Penawangan", kode: "E146" },
		{ nama: "Pulokulon", kode: "E147" },
		{ nama: "Purwodadi", kode: "E148" },
		{ nama: "Tanggungharjo", kode: "E149" },
		{ nama: "Tawangharjo", kode: "E150" },
		{ nama: "Tegowanu", kode: "E151" },
		{ nama: "Toroh", kode: "E152" },
		{ nama: "Wirosari", kode: "E153" },
		{ nama: "Geyer", kode: "E154" }
	],
    "10": [  // Kabupaten Jepara
		{ nama: "Bangsri", kode: "E155" },
		{ nama: "Batealit", kode: "E156" },
		{ nama: "Donorojo", kode: "E157" },
		{ nama: "Jepara", kode: "E158" },
		{ nama: "Kalinyamatan", kode: "E159" },
		{ nama: "Karimunjawa", kode: "E160" },
		{ nama: "Kedung", kode: "E161" },
		{ nama: "Keling", kode: "E162" },
		{ nama: "Kembang", kode: "E163" },
		{ nama: "Mayong", kode: "E164" },
		{ nama: "Mlongo", kode: "E165" },
		{ nama: "Nalumsari", kode: "E166" },
		{ nama: "Pakis Aji", kode: "E167" },
		{ nama: "Pecangaan", kode: "E168" },
		{ nama: "Tahunan", kode: "E169" },
		{ nama: "Welahan", kode: "E170" }
	],
   "11": [  // Kabupaten Karanganyar
        { nama: "Colomadu", kode: "E171" },
        { nama: "Gondangrejo", kode: "E172" },
        { nama: "Jaten", kode: "E173" },
        { nama: "Jenawi", kode: "E174" },
        { nama: "Jumantono", kode: "E175" },
        { nama: "Jumapolo", kode: "E176" },
        { nama: "Karanganyar", kode: "E177" },
        { nama: "Karangpandan", kode: "E178" },
        { nama: "Kebakkramat", kode: "E179" },
        { nama: "Matesih", kode: "E180" },
        { nama: "Mojogedang", kode: "E181" },
        { nama: "Ngargoyoso", kode: "E182" },
        { nama: "Tasikmadu", kode: "E183" },
        { nama: "Tawangmangu", kode: "E184" }
    ],
    "12": [  // Kabupaten Kebumen
        { nama: "Adimulyo", kode: "E185" },
        { nama: "Alian", kode: "E186" },
        { nama: "Ambal", kode: "E187" },
        { nama: "Ayah", kode: "E188" },
        { nama: "Bonorowo", kode: "E189" },
        { nama: "Buayan", kode: "E190" },
        { nama: "Buluspesantren", kode: "E191" },
        { nama: "Gombong", kode: "E192" },
        { nama: "Karanganyar", kode: "E193" },
        { nama: "Karanggayam", kode: "E194" },
        { nama: "Karangsambung", kode: "E195" },
        { nama: "Kebumen", kode: "E196" },
        { nama: "Klirong", kode: "E197" },
        { nama: "Kutowinangun", kode: "E198" },
        { nama: "Kuwarasan", kode: "E199" },
        { nama: "Mirit", kode: "E200" },
        { nama: "Padureso", kode: "E201" },
        { nama: "Pejagoan", kode: "E202" },
        { nama: "Petanahan", kode: "E203" },
        { nama: "Poncowarno", kode: "E204" },
        { nama: "Prembun", kode: "E205" },
        { nama: "Puring", kode: "E206" },
        { nama: "Sadang", kode: "E207" },
        { nama: "Sempor", kode: "E208" },
        { nama: "Sruweng", kode: "E209" }
    ],
    "13": [  // Kabupaten Kendal
        { nama: "Boja", kode: "E210" },
        { nama: "Brangsong", kode: "E211" },
        { nama: "Cepiring", kode: "E212" },
        { nama: "Gemuh", kode: "E213" },
        { nama: "Kaliwungu", kode: "E214" },
        { nama: "Kaliwungu Selatan", kode: "E215" },
        { nama: "Kangkung", kode: "E216" },
        { nama: "Kendal", kode: "E217" },
        { nama: "Limbangan", kode: "E218" },
        { nama: "Ngampel", kode: "E219" },
        { nama: "Pagerruyung", kode: "E220" },
        { nama: "Patean", kode: "E221" },
        { nama: "Patebon", kode: "E222" },
        { nama: "Pegandon", kode: "E223" },
        { nama: "Plantungan", kode: "E224" },
        { nama: "Ringinarum", kode: "E225" },
        { nama: "Rowosari", kode: "E226" },
        { nama: "Singorojo", kode: "E227" },
        { nama: "Sukorejo", kode: "E228" },
        { nama: "Weleri", kode: "E229" }
    ],
    "14": [  // Kabupaten Klaten
        { nama: "Bayat", kode: "E230" },
        { nama: "Cawas", kode: "E231" },
        { nama: "Ceper", kode: "E232" },
        { nama: "Delanggu", kode: "E233" },
        { nama: "Gantiwarno", kode: "E234" },
        { nama: "Jatinom", kode: "E235" },
        { nama: "Jogonalan", kode: "E236" },
        { nama: "Kalikotes", kode: "E237" },
        { nama: "Karanganom", kode: "E238" },
        { nama: "Karangdowo", kode: "E239" },
        { nama: "Karangnongko", kode: "E240" },
        { nama: "Kebonarum", kode: "E241" },
        { nama: "Kemalang", kode: "E242" },
        { nama: "Klaten Selatan", kode: "E243" },
        { nama: "Klaten Tengah", kode: "E244" },
        { nama: "Klaten Utara", kode: "E245" },
        { nama: "Manisrenggo", kode: "E246" },
        { nama: "Ngawen", kode: "E247" },
        { nama: "Pedan", kode: "E248" },
        { nama: "Polanharjo", kode: "E249" },
        { nama: "Prambanan", kode: "E250" },
        { nama: "Trucuk", kode: "E251" },
        { nama: "Tulung", kode: "E252" },
        { nama: "Wedi", kode: "E253" },
        { nama: "Wonosari", kode: "E254" }
    ],
    "15": [  // Kabupaten Kudus
        { nama: "Bae", kode: "E255" },
        { nama: "Dawe", kode: "E256" },
        { nama: "Gebog", kode: "E257" },
        { nama: "Jati", kode: "E258" },
        { nama: "Kaliwungu", kode: "E259" },
        { nama: "Kota Kudus", kode: "E260" },
        { nama: "Mejobo", kode: "E261" },
        { nama: "Undaan", kode: "E262" }
    ],
    "16": [  // Kabupaten Magelang
        { nama: "Bandongan", kode: "E263" },
        { nama: "Candimulyo", kode: "E264" },
        { nama: "Dukun", kode: "E265" },
        { nama: "Grabag", kode: "E266" },
        { nama: "Kajoran", kode: "E267" },
        { nama: "Kaliangkrik", kode: "E268" },
        { nama: "Mertoyudan", kode: "E269" },
        { nama: "Muntilan", kode: "E270" },
        { nama: "Ngablak", kode: "E271" },
        { nama: "Ngluwar", kode: "E272" },
        { nama: "Pakis", kode: "E273" },
        { nama: "Salaman", kode: "E274" },
        { nama: "Sawangan", kode: "E275" },
        { nama: "Secang", kode: "E276" },
        { nama: "Srumbung", kode: "E277" },
        { nama: "Tegalrejo", kode: "E278" },
        { nama: "Tempuran", kode: "E279" },
        { nama: "Windusari", kode: "E280" }
    ],
    "17": [  // Kabupaten Pati
        { nama: "Batangan", kode: "E281" },
        { nama: "Cluwak", kode: "E282" },
        { nama: "Dukuhseti", kode: "E283" },
        { nama: "Gabus", kode: "E284" },
        { nama: "Gembong", kode: "E285" },
        { nama: "Gunungwungkal", kode: "E286" },
        { nama: "Jaken", kode: "E287" },
        { nama: "Jakenan", kode: "E288" },
        { nama: "Juwana", kode: "E289" },
        { nama: "Kayen", kode: "E290" },
        { nama: "Margorejo", kode: "E291" },
        { nama: "Margoyoso", kode: "E292" },
        { nama: "Pati", kode: "E293" },
        { nama: "Pucakwangi", kode: "E294" },
        { nama: "Sukolilo", kode: "E295" },
        { nama: "Tambakromo", kode: "E296" },
        { nama: "Tayu", kode: "E297" },
        { nama: "Tlogowungu", kode: "E298" },
        { nama: "Trangkil", kode: "E299" },
        { nama: "Wedarijaksa", kode: "E300" },
        { nama: "Winong", kode: "E301" }
    ],
    "18": [  // Kabupaten Pekalongan
        { nama: "Bojong", kode: "E302" },
        { nama: "Doro", kode: "E303" },
        { nama: "Kajen", kode: "E304" },
        { nama: "Karangdadap", kode: "E305" },
        { nama: "Kedungwuni", kode: "E306" },
        { nama: "Limpung", kode: "E307" },
        { nama: "Petungkriyono", kode: "E308" },
        { nama: "Pekalongan Selatan", kode: "E309" },
        { nama: "Pekalongan Utara", kode: "E310" },
        { nama: "Paninggaran", kode: "E311" },
        { nama: "Siwalan", kode: "E312" },
        { nama: "Tirto", kode: "E313" },
        { nama: "Wonopringgo", kode: "E314" },
        { nama: "Wonokerto", kode: "E315" }
    ],
    "19": [  // Kabupaten Pemalang
        { nama: "Bantarbolang", kode: "E316" },
        { nama: "Belik", kode: "E317" },
        { nama: "Comal", kode: "E318" },
        { nama: "Dagangan", kode: "E319" },
        { nama: "Pemalang", kode: "E320" },
        { nama: "Petarukan", kode: "E321" },
        { nama: "Pulosari", kode: "E322" },
        { nama: "Rakit", kode: "E323" },
        { nama: "Taman", kode: "E324" },
        { nama: "Ulujami", kode: "E325" },
        { nama: "Watukumpul", kode: "E326" }
    ],
    "20": [  // Kabupaten Purbalingga
        { nama: "Bukateja", kode: "E327" },
        { nama: "Karangmoncol", kode: "E328" },
        { nama: "Kemangkon", kode: "E329" },
        { nama: "Purbalingga", kode: "E330" },
        { nama: "Rembang", kode: "E331" },
        { nama: "Bobotsari", kode: "E332" },
        { nama: "Kaligondang", kode: "E333" },
        { nama: "Karangreja", kode: "E334" },
        { nama: "Kutasari", kode: "E335" },
        { nama: "Mrebet", kode: "E336" },
        { nama: "Padamara", kode: "E337" },
        { nama: "Rembang", kode: "E338" },
        { nama: "Sumbang", kode: "E339" }
    ],
    "21": [  // Kabupaten Purworejo
        { nama: "Bener", kode: "E340" },
        { nama: "Bukur", kode: "E341" },
        { nama: "Kaligesing", kode: "E342" },
        { nama: "Kemiri", kode: "E343" },
        { nama: "Kutoarjo", kode: "E344" },
        { nama: "Ngombol", kode: "E345" },
        { nama: "Purworejo", kode: "E346" },
        { nama: "Pituruh", kode: "E347" },
        { nama: "Randublatung", kode: "E348" },
        { nama: "Reco", kode: "E349" },
        { nama: "Salaman", kode: "E350" },
        { nama: "Sidoharjo", kode: "E351" },
        { nama: "Tambak", kode: "E352" },
        { nama: "Wadaslintang", kode: "E353" },
        { nama: "Watumalang", kode: "E354" }
    ],
	"22": [  // Kabupaten Rembang
		{ nama: "Bulu", kode: "E355" },
		{ nama: "Gunem", kode: "E356" },
		{ nama: "Kaliori", kode: "E357" },
		{ nama: "Lasem", kode: "E358" },
		{ nama: "Pancur", kode: "E359" },
		{ nama: "Rembang", kode: "E360" },
		{ nama: "Sarang", kode: "E361" },
		{ nama: "Sumber", kode: "E362" },
		{ nama: "Sedan", kode: "E363" },
		{ nama: "Sluke", kode: "E364" },
		{ nama: "Sulang", kode: "E365" },
		{ nama: "Lasem", kode: "E366" }
	],
	"23": [  // Kabupaten Semarang
		{ nama: "Ambarawa", kode: "E367" },
		{ nama: "Bawen", kode: "E368" },
		{ nama: "Bergas", kode: "E369" },
		{ nama: "Boja", kode: "E370" },
		{ nama: "Cepiring", kode: "E371" },
		{ nama: "Getasan", kode: "E372" },
		{ nama: "Jambu", kode: "E373" },
		{ nama: "Kalirejo", kode: "E374" },
		{ nama: "Kembang", kode: "E375" },
		{ nama: "Ngablak", kode: "E376" },
		{ nama: "Pabelan", kode: "E377" },
		{ nama: "Pakis", kode: "E378" },
		{ nama: "Pringapus", kode: "E379" },
		{ nama: "Salatiga", kode: "E380" },
		{ nama: "Semarang", kode: "E381" },
		{ nama: "Tuntang", kode: "E382" },
		{ nama: "Ungaran Barat", kode: "E383" },
		{ nama: "Ungaran Timur", kode: "E384" }
	],
	"24": [  // Kabupaten Sragen
		{ nama: "Gemolong", kode: "E385" },
		{ nama: "Gondang", kode: "E386" },
		{ nama: "Karangmalang", kode: "E387" },
		{ nama: "Kalijambe", kode: "E388" },
		{ nama: "Miri", kode: "E389" },
		{ nama: "Ngrampal", kode: "E390" },
		{ nama: "Plupuh", kode: "E391" },
		{ nama: "Sambungmacan", kode: "E392" },
		{ nama: "Sidoharjo", kode: "E393" },
		{ nama: "Sragen", kode: "E394" },
		{ nama: "Tangen", kode: "E395" },
		{ nama: "Tanon", kode: "E396" }
	],
	"25": [  // Kabupaten Sukoharjo
		{ nama: "Baki", kode: "E397" },
		{ nama: "Gatak", kode: "E398" },
		{ nama: "Jonggol", kode: "E399" },
		{ nama: "Nguter", kode: "E400" },
		{ nama: "Sukoharjo", kode: "E401" },
		{ nama: "Tegaldowo", kode: "E402" },
		{ nama: "Tohudan", kode: "E403" },
		{ nama: "Weru", kode: "E404" }
	],
	"26": [  // Kabupaten Tegal
		{ nama: "Adiwerna", kode: "E405" },
		{ nama: "Bojong", kode: "E406" },
		{ nama: "Brebes", kode: "E407" },
		{ nama: "Dukuhturi", kode: "E408" },
		{ nama: "Jatinegara", kode: "E409" },
		{ nama: "Kramat", kode: "E410" },
		{ nama: "Margasari", kode: "E411" },
		{ nama: "Pangkah", kode: "E412" },
		{ nama: "Slawi", kode: "E413" },
		{ nama: "Sumbergempol", kode: "E414" },
		{ nama: "Tarub", kode: "E415" },
		{ nama: "Tegal", kode: "E416" },
		{ nama: "Tegal Selatan", kode: "E417" },
		{ nama: "Tegal Timur", kode: "E418" },
		{ nama: "Tegal Utara", kode: "E419" }
	],
	"27": [  // Kabupaten Temanggung
		{ nama: "Bejen", kode: "E420" },
		{ nama: "Candiroto", kode: "E421" },
		{ nama: "Jumo", kode: "E422" },
		{ nama: "Kedu", kode: "E423" },
		{ nama: "Kranggan", kode: "E424" },
		{ nama: "Parakan", kode: "E425" },
		{ nama: "Pringsurat", kode: "E426" },
		{ nama: "Temanggung", kode: "E427" },
		{ nama: "Tlogomulyo", kode: "E428" },
		{ nama: "Tretep", kode: "E429" }
	],
	"28": [  // Kabupaten Wonogiri
		{ nama: "Bulukerto", kode: "E430" },
		{ nama: "Eromoko", kode: "E431" },
		{ nama: "Giriwoyo", kode: "E432" },
		{ nama: "Jatisrono", kode: "E433" },
		{ nama: "Karangtengah", kode: "E434" },
		{ nama: "Manyaran", kode: "E435" },
		{ nama: "Ngadirojo", kode: "E436" },
		{ nama: "Purwantoro", kode: "E437" },
		{ nama: "Selogiri", kode: "E438" },
		{ nama: "Sidoharjo", kode: "E439" },
		{ nama: "Wonogiri", kode: "E440" },
		{ nama: "Wuryantoro", kode: "E441" }
	],
	"29": [  // Kota Wonosobo
		{ nama: "Garung", kode: "E442" },
		{ nama: "Jumo", kode: "E443" },
		{ nama: "Kledung", kode: "E444" },
		{ nama: "Leksono", kode: "E445" },
		{ nama: "Mojotengah", kode: "E446" },
		{ nama: "Sapuran", kode: "E447" },
		{ nama: "Wadaslintang", kode: "E448" },
		{ nama: "Wonosobo", kode: "E449" }
	],
	"30": [  // Kota Magelang 
		{ nama: "Magelang Selatan", kode: "E450" },
		{ nama: "Magelang Utara", kode: "E451" },
		{ nama: "Magelang Tengah", kode: "E452" },
		{ nama: "Mertoyudan", kode: "E453" }
	],
	"31": [  // Kota Pekalongan
		{ nama: "Pekalongan Timur", kode: "E454" },
		{ nama: "Pekalongan Utara", kode: "E455" },
		{ nama: "Pekalongan Selatan", kode: "E456" },
		{ nama: "Pekalongan Barat", kode: "E457" }
	],
	"32": [  // Kota Salatiga
		{ nama: "Argomulyo", kode: "E458" },
		{ nama: "Sidorejo", kode: "E459" },
		{ nama: "Tingkir", kode: "E460" },
		{ nama: "Salatiga", kode: "E461" }
	],
	"33": [  // Kota Semarang
		{ nama: "Semarang Barat", kode: "E462" },
		{ nama: "Semarang Selatan", kode: "E463" },
		{ nama: "Semarang Tengah", kode: "E464" },
		{ nama: "Semarang Utara", kode: "E465" }
	],
	"34": [  // Kota Surakarta (Solo)
		{ nama: "Banjarsari", kode: "E466" },
		{ nama: "Jebres", kode: "E467" },
		{ nama: "Laweyan", kode: "E468" },
		{ nama: "Pasar Kliwon", kode: "E469" },
		{ nama: "Serengan", kode: "E470" },
		{ nama: "Semanggi", kode: "E471" },
		{ nama: "Selo", kode: "E472" }
	],
	"35": [  // Kota Tegal 
		{ nama: "Tegal Barat", kode: "E473" },
		{ nama: "Tegal Timur", kode: "E474" },
		{ nama: "Margadana", kode: "E475" },
		{ nama: "Panggung", kode: "E476" }
	]

};

// Update functions remain unchanged
function updateKecamatan() {
    const kabupatenSelect = document.getElementById('kabupaten');
    const kecamatanSelect = document.getElementById('kecamatan');
    
    kecamatanSelect.innerHTML = '<option value="">Pilih Kecamatan</option>';
    
    const selectedKabupaten = kabupatenSelect.value;
    const kecamatans = kecamatanData[selectedKabupaten];
    
    if (kecamatans) {
        kecamatans.forEach(kecamatan => {
            const option = document.createElement('option');
            option.value = kecamatan.kode;
            option.textContent = kecamatan.nama;
            kecamatanSelect.appendChild(option);
        });
    }
}

function updateKodeWilayah() {
    const kecamatanSelect = document.getElementById('kecamatan');
    
    const selectedKecamatan = kecamatanSelect.value;
    
    if (selectedKecamatan) {
        const kodeWilayah = selectedKecamatan;
        document.getElementById('kode-wilayah').innerText = kodeWilayah;
        document.getElementById('contoh-output').innerText = `{${kodeWilayah}RAHMAD}`;
        document.getElementById('output').style.display = 'block';
    } else {
        document.getElementById('output').style.display = 'none';
    }
}
