const kecamatanData = {
    "01": [  // Kabupaten Asahan
        { nama: "Air Batu", kode: "H01" },
        { nama: "Air Joman", kode: "H02" },
        { nama: "Bandar Pasir Mandoge", kode: "H03" },
        { nama: "Bandar Pulau", kode: "H04" },
        { nama: "Buntu Pane", kode: "H05" },
        { nama: "Kisaran Barat", kode: "H06" },
        { nama: "Kisaran Timur", kode: "H07" },
        { nama: "Meranti", kode: "H08" },
        { nama: "Pulo Bandring", kode: "H09" },
        { nama: "Rahuning", kode: "H10" },
        { nama: "Rawang Panca Arga", kode: "H11" },
        { nama: "Sei Dadap", kode: "H12" },
        { nama: "Sei Kepayang", kode: "H13" },
        { nama: "Sei Kepayang Barat", kode: "H14" },
        { nama: "Sei Kepayang Timur", kode: "H15" },
        { nama: "Setia Janji", kode: "H16" },
        { nama: "Simpang Empat", kode: "H17" },
        { nama: "Silau Laut", kode: "H18" },
        { nama: "Tinggi Raja", kode: "H19" },
        { nama: "Tanjung Balai", kode: "H20" },
        { nama: "Teluk Dalam", kode: "H21" },
        { nama: "Aek Kuasan", kode: "H22" },
        { nama: "Aek Songsongan", kode: "H23" },
        { nama: "Aek Ledong", kode: "H24" },
        { nama: "Bandar Pulo", kode: "H25" }
    ],
    "02": [  // Kabupaten Batu Bara
        { nama: "Air Putih", kode: "H26" },
        { nama: "Datuk Lima Puluh", kode: "H27" },
        { nama: "Lima Puluh", kode: "H28" },
        { nama: "Medang Deras", kode: "H29" },
        { nama: "Sei Balai", kode: "H30" },
        { nama: "Sei Suka", kode: "H31" },
        { nama: "Talawi", kode: "H32" },
        { nama: "Tanjung Tiram", kode: "H33" },
        { nama: "Lima Puluh Pesisir", kode: "H34" },
        { nama: "Nibung Hangus", kode: "H35" },
        { nama: "Datuk Tanah Datar", kode: "H36" },
        { nama: "Laut Tador", kode: "H37" }
    ],
    "03": [  // Kabupaten Dairi
        { nama: "Berampu", kode: "H38" },
        { nama: "Gunung Sitember", kode: "H39" },
        { nama: "Lae Parira", kode: "H40" },
        { nama: "Parbuluan", kode: "H41" },
        { nama: "Sidikalang", kode: "H42" },
        { nama: "Sitinjo", kode: "H43" },
        { nama: "Sumbul", kode: "H44" },
        { nama: "Tanah Pinem", kode: "H45" },
        { nama: "Tigalingga", kode: "H46" },
        { nama: "Silima Pungga-Pungga", kode: "H47" },
        { nama: "Siempat Nempu", kode: "H48" },
        { nama: "Siempat Nempu Hulu", kode: "H49" },
        { nama: "Siempat Nempu Hilir", kode: "H50" },
        { nama: "Pegagan Hilir", kode: "H51" },
        { nama: "Parbuluan", kode: "H52" }
    ],
    "04": [  // Kabupaten Deli Serdang
        { nama: "Batang Kuis", kode: "H53" },
        { nama: "Beringin", kode: "H54" },
        { nama: "Deli Tua", kode: "H55" },
        { nama: "Galang", kode: "H56" },
        { nama: "Hamparan Perak", kode: "H57" },
        { nama: "Kutalimbaru", kode: "H58" },
        { nama: "Labuhan Deli", kode: "H59" },
        { nama: "Lubuk Pakam", kode: "H60" },
        { nama: "Namo Rambe", kode: "H61" },
        { nama: "Pancur Batu", kode: "H62" },
        { nama: "Pantai Labu", kode: "H63" },
        { nama: "Patumbak", kode: "H64" },
        { nama: "Percut Sei Tuan", kode: "H65" },
        { nama: "Sibolangit", kode: "H66" },
        { nama: "Sinembah Tanjung Muda Hilir", kode: "H67" },
        { nama: "Sinembah Tanjung Muda Hulu", kode: "H68" },
        { nama: "Sunggal", kode: "H69" },
        { nama: "Tanjung Morawa", kode: "H70" },
        { nama: "Bangun Purba", kode: "H71" },
        { nama: "STM Hulu", kode: "H72" },
        { nama: "STM Hilir", kode: "H73" },
        { nama: "Sibiru-biru", kode: "H74" }
    ],
	"06": [  // Kabupaten Karo
		{ nama: "Barusjahe", kode: "H85" },
		{ nama: "Berastagi", kode: "H86" },
		{ nama: "Dolat Rayat", kode: "H87" },
		{ nama: "Juhar", kode: "H88" },
		{ nama: "Kabanjahe", kode: "H89" },
		{ nama: "Kuta Buluh", kode: "H90" },
		{ nama: "Laubaleng", kode: "H91" },
		{ nama: "Mardingding", kode: "H92" },
		{ nama: "Merek", kode: "H93" },
		{ nama: "Merdeka", kode: "H94" },
		{ nama: "Payung", kode: "H95" },
		{ nama: "Simpang Empat", kode: "H96" },
		{ nama: "Tiga Binanga", kode: "H97" },
		{ nama: "Tiga Panah", kode: "H98" },
		{ nama: "Tiganderket", kode: "H99" },
		{ nama: "Kutabuluh", kode: "H100" },
		{ nama: "Naman Teran", kode: "H101" }
	],
	"07": [  // Kabupaten Labuhanbatu
		{ nama: "Bilah Barat", kode: "H102" },
		{ nama: "Bilah Hilir", kode: "H103" },
		{ nama: "Bilah Hulu", kode: "H104" },
		{ nama: "Panai Hilir", kode: "H105" },
		{ nama: "Panai Tengah", kode: "H106" },
		{ nama: "Panai Hulu", kode: "H107" },
		{ nama: "Pangkatan", kode: "H108" },
		{ nama: "Rantau Selatan", kode: "H109" },
		{ nama: "Rantau Utara", kode: "H110" }
	],
	"08": [  // Kabupaten Labuhanbatu Selatan
		{ nama: "Kampung Rakyat", kode: "H111" },
		{ nama: "Kotapinang", kode: "H112" },
		{ nama: "Sei Kanan", kode: "H113" },
		{ nama: "Silangkitang", kode: "H114" },
		{ nama: "Torgamba", kode: "H115" }
	],
	"09": [  // Kabupaten Labuhanbatu Utara
		{ nama: "Aek Kuo", kode: "H116" },
		{ nama: "Aek Natas", kode: "H117" },
		{ nama: "Kualuh Hilir", kode: "H118" },
		{ nama: "Kualuh Hulu", kode: "H119" },
		{ nama: "Kualuh Leidong", kode: "H120" },
		{ nama: "Kualuh Selatan", kode: "H121" },
		{ nama: "Marbau", kode: "H122" },
		{ nama: "Na IX-X", kode: "H123" }
	],
	"10": [  // Kabupaten Langkat
		{ nama: "Bahorok", kode: "H124" },
		{ nama: "Batang Serangan", kode: "H125" },
		{ nama: "Besitang", kode: "H126" },
		{ nama: "Binjai", kode: "H127" },
		{ nama: "Brandan Barat", kode: "H128" },
		{ nama: "Gebang", kode: "H129" },
		{ nama: "Hinai", kode: "H130" },
		{ nama: "Kuala", kode: "H131" },
		{ nama: "Kutambaru", kode: "H132" },
		{ nama: "Pangkalan Susu", kode: "H133" },
		{ nama: "Pematang Jaya", kode: "H134" },
		{ nama: "Salapian", kode: "H135" },
		{ nama: "Sawit Seberang", kode: "H136" },
		{ nama: "Secanggang", kode: "H137" },
		{ nama: "Sei Bingai", kode: "H138" },
		{ nama: "Sei Lepan", kode: "H139" },
		{ nama: "Selesai", kode: "H140" },
		{ nama: "Sirapit", kode: "H141" },
		{ nama: "Stabat", kode: "H142" },
		{ nama: "Tanjung Pura", kode: "H143" },
		{ nama: "Wampu", kode: "H144" },
		{ nama: "Batang Serangan", kode: "H145" },
		{ nama: "Bahorok", kode: "H146" }
	],
	"11": [  // Kabupaten Mandailing Natal
		{ nama: "Batahan", kode: "H147" },
		{ nama: "Batang Natal", kode: "H148" },
		{ nama: "Bukit Malintang", kode: "H149" },
		{ nama: "Hutabargot", kode: "H150" },
		{ nama: "Kotanopan", kode: "H151" },
		{ nama: "Lembah Sorik Marapi", kode: "H152" },
		{ nama: "Lingga Bayu", kode: "H153" },
		{ nama: "Muara Batang Gadis", kode: "H154" },
		{ nama: "Muara Sipongi", kode: "H155" },
		{ nama: "Naga Juang", kode: "H156" },
		{ nama: "Natal", kode: "H157" },
		{ nama: "Pakantan", kode: "H158" },
		{ nama: "Panyabungan", kode: "H159" },
		{ nama: "Panyabungan Barat", kode: "H160" },
		{ nama: "Panyabungan Selatan", kode: "H161" },
		{ nama: "Panyabungan Timur", kode: "H162" },
		{ nama: "Panyabungan Utara", kode: "H163" },
		{ nama: "Siabu", kode: "H164" },
		{ nama: "Sinunukan", kode: "H165" },
		{ nama: "Tambangan", kode: "H166" },
		{ nama: "Ulu Pungkut", kode: "H167" },
		{ nama: "Ranto Baek", kode: "H168" },
		{ nama: "Puncak Sorik Marapi", kode: "H169" }
	],
	"12": [  // Kabupaten Nias
		{ nama: "Bawolato", kode: "H170" },
		{ nama: "Botomuzoi", kode: "H171" },
		{ nama: "Gido", kode: "H172" },
		{ nama: "Hiliduho", kode: "H173" },
		{ nama: "Idanogawo", kode: "H174" },
		{ nama: "Ma'u", kode: "H175" },
		{ nama: "Somolo-molo", kode: "H176" },
		{ nama: "Sogaeadu", kode: "H177" },
		{ nama: "Ulugawo", kode: "H178" },
		{ nama: "Alasa", kode: "H179" }
	],
	"13": [  // Kabupaten Nias Barat
		{ nama: "Lahomi", kode: "H180" },
		{ nama: "Lolofitu Moi", kode: "H181" },
		{ nama: "Mandrehe", kode: "H182" },
		{ nama: "Mandrehe Barat", kode: "H183" },
		{ nama: "Mandrehe Utara", kode: "H184" },
		{ nama: "Moro'o", kode: "H185" },
		{ nama: "Sirombu", kode: "H186" },
		{ nama: "Ulu Moro'o", kode: "H187" }
	],
		"14": [  // Kabupaten Nias Selatan
		{ nama: "Amandraya", kode: "H188" },
		{ nama: "Aramo", kode: "H189" },
		{ nama: "Bawolato", kode: "H190" },
		{ nama: "Fanayama", kode: "H191" },
		{ nama: "Gomo", kode: "H192" },
		{ nama: "Hibala", kode: "H193" },
		{ nama: "Hilimegai", kode: "H194" },
		{ nama: "Huruna", kode: "H195" },
		{ nama: "Lahusa", kode: "H196" },
		{ nama: "Lolowau", kode: "H197" },
		{ nama: "Luahagundre Maniamolo", kode: "H198" },
		{ nama: "Maniamolo", kode: "H199" },
		{ nama: "Mazino", kode: "H200" },
		{ nama: "Mazo", kode: "H201" },
		{ nama: "Onohazumba", kode: "H202" },
		{ nama: "O'o'u", kode: "H203" },
		{ nama: "Pulau-pulau Batu", kode: "H204" },
		{ nama: "Pulau-pulau Batu Barat", kode: "H205" },
		{ nama: "Pulau-pulau Batu Timur", kode: "H206" },
		{ nama: "Pulau-pulau Batu Utara", kode: "H207" },
		{ nama: "Sidua'ori", kode: "H208" },
		{ nama: "Simuk", kode: "H209" },
		{ nama: "Somambawa", kode: "H210" },
		{ nama: "Susua", kode: "H211" },
		{ nama: "Teluk Dalam", kode: "H212" },
		{ nama: "Toma", kode: "H213" },
		{ nama: "Ulunoyo", kode: "H214" },
		{ nama: "Umbunasi", kode: "H215" },
		{ nama: "Ulususua", kode: "H216" },
		{ nama: "Hilisalawa'ahe", kode: "H217" },
		{ nama: "Hiligeho", kode: "H218" },
		{ nama: "Lolomatua", kode: "H219" },
		{ nama: "Hilisondrekha", kode: "H220" }
	],
	"15": [  // Kabupaten Nias Utara
		{ nama: "Alasa", kode: "H221" },
		{ nama: "Alasa Talumuzoi", kode: "H222" },
		{ nama: "Afulu", kode: "H223" },
		{ nama: "Lahewa", kode: "H224" },
		{ nama: "Lahewa Timur", kode: "H225" },
		{ nama: "Lotu", kode: "H226" },
		{ nama: "Namohalu Esiwa", kode: "H227" },
		{ nama: "Sawo", kode: "H228" },
		{ nama: "Sitolu Ori", kode: "H229" },
		{ nama: "Tugala Oyo", kode: "H230" },
		{ nama: "Tuhemberua", kode: "H231" }
	],
	"16": [  // Kabupaten Padang Lawas
		{ nama: "Aek Nabara Barumun", kode: "H232" },
		{ nama: "Barumun", kode: "H233" },
		{ nama: "Barumun Selatan", kode: "H234" },
		{ nama: "Barumun Tengah", kode: "H235" },
		{ nama: "Batang Lubu Sutam", kode: "H236" },
		{ nama: "Huta Raja Tinggi", kode: "H237" },
		{ nama: "Huristak", kode: "H238" },
		{ nama: "Lubuk Barumun", kode: "H239" },
		{ nama: "Sihapas Barumun", kode: "H240" },
		{ nama: "Sosa", kode: "H241" },
		{ nama: "Sosopan", kode: "H242" },
		{ nama: "Sungai Kanan", kode: "H243" },
		{ nama: "Ulu Barumun", kode: "H244" },
		{ nama: "Ujung Batu", kode: "H245" },
		{ nama: "Sosa Julu", kode: "H246" },
		{ nama: "Binanga", kode: "H247" },
		{ nama: "Aek Buaya", kode: "H248" }
	],
	"17": [  // Kabupaten Padang Lawas Utara
		{ nama: "Batang Onang", kode: "H249" },
		{ nama: "Dolok", kode: "H250" },
		{ nama: "Dolok Sigompulon", kode: "H251" },
		{ nama: "Halongonan", kode: "H252" },
		{ nama: "Halongonan Timur", kode: "H253" },
		{ nama: "Padang Bolak", kode: "H254" },
		{ nama: "Padang Bolak Julu", kode: "H255" },
		{ nama: "Portibi", kode: "H256" },
		{ nama: "Simangambat", kode: "H257" },
		{ nama: "Ujung Batu", kode: "H258" },
		{ nama: "Batang Onang", kode: "H259" },
		{ nama: "Padang Sidempuan Julu", kode: "H260" }
	],
	"18": [  // Kabupaten Pakpak Bharat
		{ nama: "Kerajaan", kode: "H261" },
		{ nama: "Pagindar", kode: "H262" },
		{ nama: "Pergetteng-getteng Sengkut", kode: "H263" },
		{ nama: "Salak", kode: "H264" },
		{ nama: "Sitellu Tali Urang Julu", kode: "H265" },
		{ nama: "Sitellu Tali Urang Jehe", kode: "H266" },
		{ nama: "Tinada", kode: "H267" },
		{ nama: "Siempat Rube", kode: "H268" }
	],
	"19": [  // Kabupaten Samosir
		{ nama: "Harian", kode: "H269" },
		{ nama: "Nainggolan", kode: "H270" },
		{ nama: "Onan Runggu", kode: "H271" },
		{ nama: "Palipi", kode: "H272" },
		{ nama: "Pangururan", kode: "H273" },
		{ nama: "Ronggur Nihuta", kode: "H274" },
		{ nama: "Sianjur Mulamula", kode: "H275" },
		{ nama: "Simanindo", kode: "H276" },
		{ nama: "Sitio-tio", kode: "H277" }
	],
	"20": [  // Kabupaten Serdang Bedagai
		{ nama: "Bintang Bayu", kode: "H278" },
		{ nama: "Dolok Masihul", kode: "H279" },
		{ nama: "Dolok Merawan", kode: "H280" },
		{ nama: "Kotarih", kode: "H281" },
		{ nama: "Pegajahan", kode: "H282" },
		{ nama: "Perbaungan", kode: "H283" },
		{ nama: "Sei Bamban", kode: "H284" },
		{ nama: "Sei Rampah", kode: "H285" },
		{ nama: "Serbajadi", kode: "H286" },
		{ nama: "Silinda", kode: "H287" },
		{ nama: "Sipispis", kode: "H288" },
		{ nama: "Tebing Syahbandar", kode: "H289" },
		{ nama: "Tebing Tinggi", kode: "H290" },
		{ nama: "Teluk Mengkudu", kode: "H291" },
		{ nama: "Tanjung Beringin", kode: "H292" },
		{ nama: "Bandar Khalipah", kode: "H293" },
		{ nama: "Pantai Cermin", kode: "H294" }
	],
	"21": [  // Kabupaten Simalungun
		{ nama: "Bandar", kode: "H295" },
		{ nama: "Bandar Huluan", kode: "H296" },
		{ nama: "Bandar Masilam", kode: "H297" },
		{ nama: "Bosar Maligas", kode: "H298" },
		{ nama: "Dolok Batu Nanggar", kode: "H299" },
		{ nama: "Dolok Panribuan", kode: "H300" },
		{ nama: "Dolok Pardamean", kode: "H301" },
		{ nama: "Dolok Silau", kode: "H302" },
		{ nama: "Girsang Sipangan Bolon", kode: "H303" },
		{ nama: "Gunung Malela", kode: "H304" },
		{ nama: "Gunung Maligas", kode: "H305" },
		{ nama: "Haranggaol Horisan", kode: "H306" },
		{ nama: "Hatonduhan", kode: "H307" },
		{ nama: "Jawa Maraja Bah Jambi", kode: "H308" },
		{ nama: "Jorlang Hataran", kode: "H309" },
		{ nama: "Panombeian Panei", kode: "H310" },
		{ nama: "Panei", kode: "H311" },
		{ nama: "Purba", kode: "H312" },
		{ nama: "Raya", kode: "H313" },
		{ nama: "Raya Kahean", kode: "H314" },
		{ nama: "Siantar", kode: "H315" },
		{ nama: "Siantar Marihat", kode: "H316" },
		{ nama: "Siantar Martoba", kode: "H317" },
		{ nama: "Sidamanik", kode: "H318" },
		{ nama: "Silau Kahean", kode: "H319" },
		{ nama: "Tanah Jawa", kode: "H320" },
		{ nama: "Tapian Dolok", kode: "H321" },
		{ nama: "Ujung Padang", kode: "H322" },
		{ nama: "Huta Bayu Raja", kode: "H323" },
		{ nama: "Bandar Maruhur", kode: "H324" },
		{ nama: "Lintang Batu", kode: "H325" },
		{ nama: "Mariah Bandar", kode: "H326" }
	],
	"22": [  // Kabupaten Tapanuli Selatan
		{ nama: "Angkola Barat", kode: "H327" },
		{ nama: "Angkola Sangkunur", kode: "H328" },
		{ nama: "Angkola Selatan", kode: "H329" },
		{ nama: "Angkola Timur", kode: "H330" },
		{ nama: "Batang Angkola", kode: "H331" },
		{ nama: "Batang Toru", kode: "H332" },
		{ nama: "Marancar", kode: "H333" },
		{ nama: "Muara Batang Toru", kode: "H334" },
		{ nama: "Saipar Dolok Hole", kode: "H335" },
		{ nama: "Sipirok", kode: "H336" },
		{ nama: "Tano Tombangan Angkola", kode: "H337" },
		{ nama: "Arse", kode: "H338" },
		{ nama: "Aek Bilah", kode: "H339" },
		{ nama: "Saipar Dolok Hole", kode: "H340" },
		{ nama: "Muara Angkola", kode: "H341" }
	],
	"23": [  // Kabupaten Tapanuli Tengah
		{ nama: "Andam Dewi", kode: "H342" },
		{ nama: "Badiri", kode: "H343" },
		{ nama: "Barus", kode: "H344" },
		{ nama: "Barus Utara", kode: "H345" },
		{ nama: "Kolang", kode: "H346" },
		{ nama: "Lumut", kode: "H347" },
		{ nama: "Manduamas", kode: "H348" },
		{ nama: "Pasaribu Tobing", kode: "H349" },
		{ nama: "Pinangsori", kode: "H350" },
		{ nama: "Sarudik", kode: "H351" },
		{ nama: "Sorkam", kode: "H352" },
		{ nama: "Sorkam Barat", kode: "H353" },
		{ nama: "Sosor Gadong", kode: "H354" },
		{ nama: "Sitahuis", kode: "H355" },
		{ nama: "Sibabangun", kode: "H356" },
		{ nama: "Sirandorung", kode: "H357" },
		{ nama: "Sirandorung Barat", kode: "H358" },
		{ nama: "Tapian Nauli", kode: "H359" },
		{ nama: "Tukka", kode: "H360" },
		{ nama: "Pandan", kode: "H361" }
	],
	"24": [  // Kabupaten Tapanuli Utara
		{ nama: "Adian Koting", kode: "H362" },
		{ nama: "Garoga", kode: "H363" },
		{ nama: "Muara", kode: "H364" },
		{ nama: "Pagaran", kode: "H365" },
		{ nama: "Pahae Jae", kode: "H366" },
		{ nama: "Pahae Julu", kode: "H367" },
		{ nama: "Parmonangan", kode: "H368" },
		{ nama: "Purbatua", kode: "H369" },
		{ nama: "Siborong-Borong", kode: "H370" },
		{ nama: "Sipoholon", kode: "H371" },
		{ nama: "Simangumban", kode: "H372" },
		{ nama: "Tarutung", kode: "H373" },
		{ nama: "Siatas Barita", kode: "H374" },
		{ nama: "Sitoluama", kode: "H375" },
		{ nama: "Pangaribuan", kode: "H376" }
	],
	"25": [  // Kabupaten Toba
		{ nama: "Ajibata", kode: "H377" },
		{ nama: "Balige", kode: "H378" },
		{ nama: "Bonatua Lunasi", kode: "H379" },
		{ nama: "Borbor", kode: "H380" },
		{ nama: "Habinsaran", kode: "H381" },
		{ nama: "Laguboti", kode: "H382" },
		{ nama: "Lumban Julu", kode: "H383" },
		{ nama: "Nassau", kode: "H384" },
		{ nama: "Parmaksian", kode: "H385" },
		{ nama: "Pintu Pohan Meranti", kode: "H386" },
		{ nama: "Porsea", kode: "H387" },
		{ nama: "Siantar Narumonda", kode: "H388" },
		{ nama: "Sigumpar", kode: "H389" },
		{ nama: "Silaen", kode: "H390" },
		{ nama: "Tampahan", kode: "H391" },
		{ nama: "Uluan", kode: "H392" }
	],
	"26": [  // Kota Binjai
		{ nama: "Binjai Barat", kode: "H393" },
		{ nama: "Binjai Kota", kode: "H394" },
		{ nama: "Binjai Selatan", kode: "H395" },
		{ nama: "Binjai Timur", kode: "H396" },
		{ nama: "Binjai Utara", kode: "H397" }
	],
	"27": [  // Kota Gunungsitoli
		{ nama: "Gunungsitoli", kode: "H398" },
		{ nama: "Gunungsitoli Alo'oa", kode: "H399" },
		{ nama: "Gunungsitoli Barat", kode: "H400" },
		{ nama: "Gunungsitoli Idanoi", kode: "H401" },
		{ nama: "Gunungsitoli Selatan", kode: "H402" },
		{ nama: "Gunungsitoli Utara", kode: "H403" }
	],
	"28": [  // Kota Medan
		{ nama: "Medan Amplas", kode: "H404" },
		{ nama: "Medan Area", kode: "H405" },
		{ nama: "Medan Barat", kode: "H406" },
		{ nama: "Medan Belawan", kode: "H407" },
		{ nama: "Medan Deli", kode: "H408" },
		{ nama: "Medan Denai", kode: "H409" },
		{ nama: "Medan Helvetia", kode: "H410" },
		{ nama: "Medan Johor", kode: "H411" },
		{ nama: "Medan Kota", kode: "H412" },
		{ nama: "Medan Labuhan", kode: "H413" },
		{ nama: "Medan Maimun", kode: "H414" },
		{ nama: "Medan Marelan", kode: "H415" },
		{ nama: "Medan Perjuangan", kode: "H416" },
		{ nama: "Medan Petisah", kode: "H417" },
		{ nama: "Medan Polonia", kode: "H418" },
		{ nama: "Medan Selayang", kode: "H419" },
		{ nama: "Medan Sunggal", kode: "H420" },
		{ nama: "Medan Tembung", kode: "H421" },
		{ nama: "Medan Timur", kode: "H422" },
		{ nama: "Medan Tuntungan", kode: "H423" },
		{ nama: "Medan Baru", kode: "H424" }
	],
	"29": [  // Kota Padang Sidempuan
		{ nama: "Padang Sidempuan Angkola Julu", kode: "H425" },
		{ nama: "Padang Sidempuan Batunadua", kode: "H426" },
		{ nama: "Padang Sidempuan Hutaimbaru", kode: "H427" },
		{ nama: "Padang Sidempuan Selatan", kode: "H428" },
		{ nama: "Padang Sidempuan Tenggara", kode: "H429" },
		{ nama: "Padang Sidempuan Utara", kode: "H430" }
	],
	"30": [  // Kota Pematangsiantar
		{ nama: "Siantar Barat", kode: "H431" },
		{ nama: "Siantar Marihat", kode: "H432" },
		{ nama: "Siantar Marimbun", kode: "H433" },
		{ nama: "Siantar Martoba", kode: "H434" },
		{ nama: "Siantar Selatan", kode: "H435" },
		{ nama: "Siantar Sitalasari", kode: "H436" },
		{ nama: "Siantar Timur", kode: "H437" },
		{ nama: "Siantar Utara", kode: "H438" }
	],
	"31": [  // Kota Sibolga
		{ nama: "Sibolga Kota", kode: "H439" },
		{ nama: "Sibolga Sambas", kode: "H440" },
		{ nama: "Sibolga Selatan", kode: "H441" },
		{ nama: "Sibolga Utara", kode: "H442" }
	],
	"32": [  // Kota Tanjungbalai
		{ nama: "Datuk Bandar", kode: "H443" },
		{ nama: "Datuk Bandar Timur", kode: "H444" },
		{ nama: "Sei Tualang Raso", kode: "H445" },
		{ nama: "Tanjung Balai Selatan", kode: "H446" },
		{ nama: "Tanjung Balai Utara", kode: "H447" },
		{ nama: "Teluk Nibung", kode: "H448" }
	],
	"33": [  // Kota Tebing Tinggi
		{ nama: "Bajenis", kode: "H449" },
		{ nama: "Padang Hilir", kode: "H450" },
		{ nama: "Padang Hulu", kode: "H451" },
		{ nama: "Rambutan", kode: "H452" },
		{ nama: "Tebing Tinggi Kota", kode: "H453" }
	]

};




// Update functions remain unchanged
function updateKecamatan() {
    const kabupatenSelect = document.getElementById('kabupaten');
    const kecamatanSelect = document.getElementById('kecamatan');
    
    kecamatanSelect.innerHTML = '<option value="">Pilih Kecamatan</option>';
    
    const selectedKabupaten = kabupatenSelect.value;
    const kecamatans = kecamatanData[selectedKabupaten];
    
    if (kecamatans) {
        kecamatans.forEach(kecamatan => {
            const option = document.createElement('option');
            option.value = kecamatan.kode;
            option.textContent = kecamatan.nama;
            kecamatanSelect.appendChild(option);
        });
    }
}

function updateKodeWilayah() {
    const kecamatanSelect = document.getElementById('kecamatan');
    
    const selectedKecamatan = kecamatanSelect.value;
    
    if (selectedKecamatan) {
        const kodeWilayah = selectedKecamatan;
        document.getElementById('kode-wilayah').innerText = kodeWilayah;
        document.getElementById('contoh-output').innerText = `{${kodeWilayah}RAHMAD}`;
        document.getElementById('output').style.display = 'block';
    } else {
        document.getElementById('output').style.display = 'none';
    }
}
